export const USERS_LIST = [
  {
    userId: 1,
    userName: "John Doe",
    email: "john.doe@rentals.com",
    password: "*******",
    phone: "+30 690 111 2222",
    role: ROLES.OWNER,
  },
  {
    userId: 2,
    userName: "Jane Smith",
    email: "jane.smith@rentals.com",
    password: "*******",
    phone: "+30 690 222 3333",
    role: ROLES.OWNER,
  },
  {
    userId: 3,
    userName: "Admin User",
    email: "admin@rentals.com",
    password: "*******",
    phone: "+30 690 333 4444",
    role: ROLES.ADMIN,
    adminStatus: true,
  },
  {
    userId: 4,
    userName: "Real Estate Agency",
    email: "agency@rentals.com",
    password: "*******",
    phone: "+30 690 444 5555",
    role: ROLES.AGENCY,
  },
  {
    userId: 5,
    userName: "Tenant User",
    email: "tenant@rentals.com",
    password: "*******",
    phone: "+30 690 555 6666",
    role: ROLES.CUSTOMER,
    budget: 1000,
    location: "Athens",
  },
  {
    userId: 6,
    userName: "Another Customer",
    email: "another.customer@rentals.com",
    password: "*******",
    phone: "+30 690 666 7777",
    role: ROLES.CUSTOMER,
    budget: 1500,
    location: "Piraeus",
  },
  {
    userId: 7,
    userName: "Yet Another Customer",
    email: "yet.another.customer@rentals.com",
    password: "*******",
    phone: "+30 690 777 8888",
    role: ROLES.CUSTOMER,
    budget: 800,
    location: "Nea Ionia",
  },
];
