export const columnsDefs = [
    {field: 'checkInStatus', headerName: 'Check In Status', width: 200},
    {field: 'name', headerName: 'Name', width: 200},
    {field: 'lastName', headerName: 'Last Name', width: 200},
    {field: 'email', headerName: 'Email', width: 200},
    {field: 'phone', headerName: 'Phone', width: 200},
    {field: 'movieTitle', headerName: 'Movie Title', width: 180},
    {field: 'screenName', headerName: 'Screen Name', width: 180},
    {field: 'startTime', headerName: 'Start Time', width: 130},
    {field: 'endTime', headerName: 'End Time', width: 130},
    {field: 'eventDate', headerName: 'Event Date', width: 130},
    {field: 'seat', headerName: 'Seat', width: 100},
    {field: 'type', headerName: 'Type', width: 100},
    {field: 'price', headerName: 'Price', width: 100},
    {field: 'status', headerName: 'Status', width: 130},
    {field: 'wantsEmailNotifications', headerName: 'Email Notifications', width: 80, type: 'boolean'},
    {field: 'reservationCode', headerName: 'Code', width: 160},
    {field: 'reservationId', headerName: 'Reservation Id', width: 130},
];